#!/usr/bin/env python
import Interpeter, sys, time, pathlib, os
os.system(f"chmod +x {__file__}")
def Run():
  '''
  This Is the "Run" Function Which Takes the Beyond Brainfuck Code
  And Gives In the Terminal Results. Such as Errors, Warnings, Outputs
  And More. You can Specify Settings On a "BBF.config.json" File For
  How The Interpreter Will Work
  '''
  if len ( sys.argv ) < 3 :
    print ( "\033[31m\033[0m\033[1;31mNo Beyond Brainfuck File Has Been Specified" )
    return
  with open(file = sys.argv[2], mode = "r") as f:
    if len(sys.argv) < 4:
      print("\033[31m\033[0m\033[1;31mNo Beyond Brainfuck Config File Has Been Specified")
      return
    config_file = sys.argv[3]
    Interpeter.Transform(f.read(), config_file)

def Setup():
  '''
  This is the "Setup" Function Which all it Does Is Well Set up
  The Files for You to Code In Beyond Brainfuck, It Creates a Config File
  As Well as Your .BFF File,

  There are Flags that Can Be Used to Alter the Way the Function Will Work
  Here are Some Flags that Might Come Handy in Some Situations:

  --template :: Generates a Template Code In the .bff File
  '''
  TemplateGeneration = False
  if len(sys.argv) < 3:
    print ( "\033[31m\033[0m\033[1;31mNo Path To Deliver the Files Has Been Specified" )
    return
  if len(sys.argv) < 4:
    print ( "\033[31m\033[0m\033[1;31mNo BBF File Name Has Been Specified" )
    return
  Path = os.path.expanduser(sys.argv[2])
  if not os.path.exists(Path):
    print ( "\033[31m\033[0m\033[1;31mPath Doesn't Exist, Rename It" )
    return
  Filename = sys.argv[3]
  if os.path.exists(f"{Path}/{os.path.splitext(Filename)[0]}-BFF"):
    print ( "\033[31m\033[0m\033[1;31mFolder Already Exists with that Name In the Parent Folder" )
    return
  os.mkdir(path = f"{Path}/{os.path.splitext(Filename)[0]}-BFF")
  Template_Code = ""
  with open (Filename, 'w') as f:
    f.write("")

if sys.argv[1] == "--run":
  Run()
elif sys.argv[1] == "--create":
  Setup()